import os
import sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))


from fastapi import APIRouter
from fastapi.responses import FileResponse
from schemas.usermessage import user_message
from services.ai_service import generate_response
from pydantic import BaseModel
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter


router = APIRouter()

class HealthData(BaseModel):
    name: str
    email: str
    heart_rate: str
    sleep: str
    activity: str
    risk: str


# ----------------------------
# Generate PDF Endpoint
# ----------------------------
@router.post("/generate-pdf")
def generate_pdf(
    data: HealthData = None,
    name: str = "Unknown User",
    email: str = "Not Provided",
    heart_rate: str = "72 bpm",
    sleep: str = "78%",
    activity: str = "65%",
    risk: str = "18/100"
):
    filename = "lifeguard_health_report.pdf"
    c = canvas.Canvas(filename, pagesize=letter)

    c.setFont("Helvetica-Bold", 18)
    c.drawString(170, 760, "LIFEGUARD HEALTH REPORT")

    c.setFont("Helvetica", 12)

    # If POST → use body
    if data:
        name = data.name
        email = data.email
        heart_rate = data.heart_rate
        sleep = data.sleep
        activity = data.activity
        risk = data.risk

    # PDF text
    c.drawString(80, 720, f"Name: {name}")
    c.drawString(80, 700, f"Email: {email}")
    c.drawString(80, 660, f"Heart Rate: {heart_rate}")
    c.drawString(80, 640, f"Sleep Quality: {sleep}")
    c.drawString(80, 620, f"Activity Level: {activity}")
    c.drawString(80, 600, f"Risk Score: {risk}")
    c.drawString(80, 560, "Generated by LifeGuard Digital Health Twin")

    c.save()

    return FileResponse(
        filename,
        media_type="application/pdf",
        filename=filename
    )
